Script started on Wed Feb 16 21:14:48 2022
[1m[7m%[27m[1m[0m                                                                                                                                                                                                            ]7;file://moes.local/Users/moe/Desktop[0m[27m[24m[Jmoe@moes Desktop % [K[?2004hggcc game.c -pthread -o game[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                            ]7;file://moes.local/Users/moe/Desktop[0m[27m[24m[Jmoe@moes Desktop % [K[?2004h../c game[1m [0m[0m [?2004l

[0] = 4	[1] = 9	[2] = 3	
[3] = 5	[4] = 7	[5] = 2	
[6] = 6	[7] = 1	[8] = 8	

The winner is player 2

[1m[7m%[27m[1m[0m                                                                                                                                                                                                            ]7;file://moes.local/Users/moe/Desktop[0m[27m[24m[Jmoe@moes Desktop % [K[?2004h./game[?2004l

[0] = 7	[1] = 8	[2] = 9	
[3] = 3	[4] = 2	[5] = 5	
[6] = 4	[7] = 6	[8] = 1	

The winner is player 2

[1m[7m%[27m[1m[0m                                                                                                                                                                                                            ]7;file://moes.local/Users/moe/Desktop[0m[27m[24m[Jmoe@moes Desktop % [K[?2004h./game[?2004l

[0] = 1	[1] = 7	[2] = 3	
[3] = 2	[4] = 9	[5] = 4	
[6] = 6	[7] = 8	[8] = 5	

The winner is player 1

[1m[7m%[27m[1m[0m                                                                                                                                                                                                            ]7;file://moes.local/Users/moe/Desktop[0m[27m[24m[Jmoe@moes Desktop % [K[?2004h./game[?2004l

[0] = 1	[1] = 4	[2] = 3	
[3] = 8	[4] = 6	[5] = 7	
[6] = 5	[7] = 9	[8] = 2	

Its a draw!!

[1m[7m%[27m[1m[0m                                                                                                                                                                                                            ]7;file://moes.local/Users/moe/Desktop[0m[27m[24m[Jmoe@moes Desktop % [K[?2004h./game[?2004l

[0] = 9	[1] = 7	[2] = 8	
[3] = 3	[4] = 2	[5] = 1	
[6] = 6	[7] = 4	[8] = 5	

The winner is player 1

[1m[7m%[27m[1m[0m                                                                                                                                                                                                            ]7;file://moes.local/Users/moe/Desktop[0m[27m[24m[Jmoe@moes Desktop % [K[?2004h./game[?2004l

[0] = 9	[1] = 7	[2] = 8	
[3] = 3	[4] = 2	[5] = 1	
[6] = 6	[7] = 4	[8] = 5	

The winner is player 1

[1m[7m%[27m[1m[0m                                                                                                                                                                                                            ]7;file://moes.local/Users/moe/Desktop[0m[27m[24m[Jmoe@moes Desktop % [K[?2004h./game[?2004l

[0] = 5	[1] = 9	[2] = 3	
[3] = 2	[4] = 4	[5] = 8	
[6] = 6	[7] = 1	[8] = 7	

Its a draw!!

[1m[7m%[27m[1m[0m                                                                                                                                                                                                            ]7;file://moes.local/Users/moe/Desktop[0m[27m[24m[Jmoe@moes Desktop % [K[?2004heexit[?2004l

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Script done on Wed Feb 16 21:15:18 2022
